services:
  backend:
    build:
      context: ./k_back
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./k_back:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DEV_DATABASE_URL}
      TEST_DATABASE_URL: ${DEV_TEST_DATABASE_URL}
