name: CD for Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Dockerfileのバージョンに合わせました

      - name: Install dependencies
        working-directory: ./k_back
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Pytest
        working-directory: ./k_back
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: pytest

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run using Cloud Build
        working-directory: ./k_back
        run: gcloud builds submit --config cloudbuild.yaml .
